# Generated by Django 4.1.3 on 2022-11-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taks_id', models.AutoField(primary_key=True, serialize=False, verbose_name='taks_id')),
                ('task_title', models.CharField(max_length=255, verbose_name='task_title')),
                ('task_date', models.DateField(verbose_name='task_date')),
                ('task_description', models.TextField(max_length=255, verbose_name='task_description')),
                ('task_status', models.BooleanField(default=True)),
            ],
        ),
    ]
