# Generated by Django 4.1.3 on 2022-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('clave', models.CharField(max_length=255, verbose_name='clave')),
            ],
        ),
    ]
