# Generated by Django 3.2.8 on 2022-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosTareas',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreUsuario', models.CharField(max_length=255, verbose_name='Usuario')),
                ('claveUsuario', models.CharField(max_length=255, verbose_name='Contraseña')),
            ],
        ),
    ]
