# Generated by Django 4.1.3 on 2022-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tasks_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='user_id'),
        ),
    ]
